Initial fs service support
rust3ds/ctru-rs-old pull request #10
Opened 2016-08-19 07:56 UTC by FenrirWolf

I'm not sure if this PR is ready for merging yet, but I would like to get some comments on a few of the things I did here.

For one, I ported a few APIs from the standard library. Specifically, I ported the Path API and its dependencies (OsString and Ascii), making sure that they passed their unit tests before adding them in. OsString itself is based on the standard library's Wtf8 module, since apparently the 3DS models its internal filepath strings the same way that Windows does: as an opaque sequence of WCHARs that might or might not be valid UTF-16.

Secondly, this PR, if implemented, would require that end users manually update their copy of ctrulib to the latest version from github. A number of changes have been made to ctrulib since 1.1 came out, including ones that make the FS service much more bearable to work with than before. Many homebrew devs have moved on from 1.1 at this point, so end users already have to update ctrulib to compile most other modern homebrew anyway.

With that out of the way, here's a rundown of how FS services work on the 3DS:

1. The fs module is initialized
2. The user opens an *archive*, such as the sdmc archive (SD card), save file archives, extdata archives, NAND archives, etc.
3. The user opens a file within that archive. There are APIs to manipulate files, copy files between different archives, and so on.

This PR includes functions for manipulating files on the sdmc archive as an example of how to encode the above pattern into Rust's type system. The same pattern should work for the other archives, though it is worth noting that some archives are opened using specific binary paths rather than WCHAR or ASCII strings. Binary paths for those archives can be defined at a later point.

2016-08-30 04:38 UTC, HybridEidolon commented
This is definitely gonna take some time to review, sorry for the wait.

2016-09-22 06:56 UTC, FenrirWolf commented on src/services/fs.rs
> +    }
This works for 3dsx homebrew, but apparently CIA applications require some extra work to manually init fs:USER. Could probably be done with conditional compilation, though doing so right now isn't all that urgent.

2016-09-22 06:59 UTC, FenrirWolf commented on src/services/fs.rs
> +                FS_WRITE_FLUSH | FS_WRITE_UPDATE_TIME
Not yet sure if these FS_WRITE flags are necessary, nor am I sure if they cause conflicts when used in non-sdmc archives.

2016-09-22 07:06 UTC, FenrirWolf commented on src/services/fs.rs
> +    }
Should this function also call sdmc::Sdmc::init()? The service was already initialized by ctrulib's `__appInit()` function, which is why this currently works as-is. On that note, should we stub out `__appInit()` so that all service init is controlled purely by Rust?

2016-09-29 19:18 UTC, FenrirWolf commented
Okay, I think I'm done adding stuff for this PR other than documentation.

2016-10-03 16:49 UTC, HybridEidolon requested changes
The use of code from rustc should be mentioned in the README's license section, just stick the Apache license excerpt in there. Other than that, it's good to go.

2016-10-03 16:49 UTC, HybridEidolon commented on src/services/fs.rs
> +    }
Is that what you mean by returning `Err` depending on the execution environment? It's probably worth mentioning in the doc even if we're not going to worry about it for now.

2016-10-03 16:49 UTC, HybridEidolon commented on src/services/fs.rs
> +    }
Ahh yes, the awkwardness of C APIs in Rust rears its ugly head again. If I recall, ctrulib's sdmc system is a layer to interface with stdio functions? If your IO functionality only uses the 3DS system calls (as far as I can tell so far, that seems to be the case), then you probably don't need to worry about it.

It's _probably_ worth supplying our own `__appInit` to ensure there's no hidden behavior that can't be accounted for by Rust. It wouldn't be as much of a problem if they were reference counted the way SDL handles its subsystems. But for now, let's not override it, and let's also not call `sdmc::Sdmc::init` either.

If this fs layer provides all the functionality of `sdmc` then we can probably just drop that entirely.

2016-10-03 16:49 UTC, HybridEidolon commented on src/services/fs.rs
> +    /// use ctru::servies::fs::{Fs, File};
Minor typo `servies => services`, there's another one for the same example on `create`.

2016-10-03 16:49 UTC, HybridEidolon commented on src/services/fs.rs
> +fn to_utf16(path: &Path) -> Vec<u16> {
Don't we have the `rustc_unicode` crate available? Is there any particular reason you're not using stuff from there here? I think some UTF-16 related functionality was recently stabilized in std, which itself derives from that crate.

2016-10-03 18:37 UTC, FenrirWolf commented on src/services/fs.rs
> +fn to_utf16(path: &Path) -> Vec<u16> {
`rustc_unicode` functions are used under the hood in the sys/wtf8 module, which is being used as the underlying implementation of `OsStr`. I chose that implementation on the assumption that the 3DS might deal in sometimes-malformed-utf16 paths in the same way that Windows does, but on further reflection I'm not completely sure if that's the case or not. If 3DS filepaths are always well-formed then `OsStr` could probably be represented as a normal `str` under the hood instead.

2016-10-03 18:56 UTC, FenrirWolf commented
For some reason I can't directly reply to the comment about service initialization, so I'll just do it here: ctrulib services actually are all reference counted, so it's probably not even necessary to override `__AppInit()`. In fact, doing so would be somewhat of an inconvenience since some things like the `srv` service operate under the hood even if you aren't explicitly calling them on the Rust side.

2016-10-03 19:28 UTC, HybridEidolon approved these changes

2016-10-03 19:29 UTC, merged